instructions_path="/home/erik/Myelin/instructions"

model_path="/home/erik/Myelin/models/Llama-3.2-3B-Instruct-f16.gguf"
; model_path="/home/erik/Myelin/models/Llama-3.2-1B-Instruct-f16.gguf"

n_ctx=4096
n_threads=6          ; Núcleos físicos para geração (estabilidade)
n_threads_batch=12   ; Todos os núcleos para o impacto inicial
n_batch=128          ; Diminuir o batch aqui ajuda a CPU a começar a "cuspir" tokens mais rápido
max_tokens=500       ; Limite para evitar que ela escreva redações desnecessárias